language: php
php:
 - '7.0'
 - '5.6'
 - '5.5'

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev

script:
- ./vendor/bin/phpunit --coverage-clover clover.xml

after_script:
- php vendor/bin/coveralls -v

install:
 - composer install

script:
- vendor/bin/phpcs --standard=PSR2 app
- vendor/bin/phpcs --standard=PSR2 tests
- vendor/bin/phpmd  app text codesize,unusedcode,naming,cleancode,design,controversial
- vendor/bin/phpunit --coverage-clover clover.xml tests/TestMathLibrary.php
