language: php
php:
 - '7.0'
 - '5.6'
 - '5.5'

install:
 - composer install

script:
- vendor/bin/phpcs --standard=PSR2 app
- vendor/bin/phpcs --standard=PSR2 tests
- vendor/bin/phpunit tests/TestMathLibrary.php


