language: php
php:
 - '7.0'
 - '5.6'
 - '5.5'

install:
 - composer install

script:
- vendor/bin/phpcs --standard=PSR2 app
- vendor/bin/phpcs --standard=PSR2 tests
- vendor/bin/phpmd  app text codesize,unusedcode,naming,cleancode,design,controversial
- vendor/bin/phpunit --code-coverage=clover.xml tests/TestMathLibrary.php
